# Simulated request every 10 minutes to your render project so that the service doesn't go down
name: Render ping every 10 minutes
on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering
jobs:
  curl-website:
    runs-on: ubuntu-latest
    steps:
      - name: Run cURL on Website
        run: curl -I https://albatros-back.onrender.com
